[phases.setup]
nixPkgs = ["python311", "glib", "libGL", "tesseract", "zbar"]

[phases.install]
cmds = [
    "pip install --no-cache-dir -r requirements.txt",
    "pip uninstall opencv-python opencv-contrib-python -y -q || true",
    "pip install --no-cache-dir opencv-python-headless --force-reinstall -q"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT}"
