[phases.setup]
nixPkgs = ["python311", "libglib", "tesseract", "zbar"]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt",
  "pip install opencv-python-headless --force-reinstall -q"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
MISE_PYTHON_GITHUB_ATTESTATIONS = "false"
QT_QPA_PLATFORM = "offscreen"
MPLBACKEND = "Agg"
DISPLAY = ""
OPENCV_IO_ENABLE_OPENEXR = "0"
